/* generated by Makefile.devel from version.sh */
#define PACKAGE_NAME "GNU CLISP"
#define PACKAGE_TARNAME "clisp"
#define PACKAGE_VERSION "2.38 (2006-01-24)"
#define PACKAGE_STRING "GNU CLISP 2.38 (2006-01-24)"
#define PACKAGE_BUGREPORT "http://clisp.cons.org/"
