(PROGN (IN-PACKAGE "SYS") T)      T

(MAKE-HASH-TABLE :TEST (QUOTE EQ) :SIZE 20)
#S(HASH-TABLE TEST EQ SIZE 20 %%SIZE 64 REHASH-SIZE 2.0 %%REHASH-SIZE 2
       REHASH-THRESHOLD 13 %%REHASH-THRESHOLD 13 %%COUNT 0 %%HASH-VEKTOR
       #(%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT))

(MAKE-HASH-TABLE :TEST (QUOTE EQL) :SIZE 2)
#S(HASH-TABLE TEST EQL SIZE 2 %%SIZE 4 REHASH-SIZE 2.0 %%REHASH-SIZE 2
       REHASH-THRESHOLD 13 %%REHASH-THRESHOLD 2 %%COUNT 0 %%HASH-VEKTOR
       #(%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT))

(MAKE-HASH-TABLE :TEST (QUOTE EQUAL) :SIZE 2)
#S(HASH-TABLE TEST EQUAL SIZE 2 %%SIZE 4 REHASH-SIZE 2.0 %%REHASH-SIZE 2
       REHASH-THRESHOLD 13 %%REHASH-THRESHOLD 2 %%COUNT 0 %%HASH-VEKTOR
       #(%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT))

(Progn (MAKE-HASH-TABLE :TEST (FUNCTION EQ) :SIZE 2) t) t

(PROGN (MAKE-HASH-TABLE :TEST (FUNCTION EQL) :SIZE 2)T) T

(MAKE-HASH-TABLE :SIZE NIL)
ERROR

(MAKE-HASH-TABLE :SIZE -3)
ERROR

(MAKE-HASH-TABLE :SIZE 2.0)
ERROR

(MAKE-HASH-TABLE :SIZE 2 :REHASH-SIZE 1.5)
#S(HASH-TABLE TEST EQL SIZE 2 %%SIZE 4 REHASH-SIZE 1.5 %%REHASH-SIZE 2
       REHASH-THRESHOLD 13 %%REHASH-THRESHOLD 2 %%COUNT 0 %%HASH-VEKTOR
       #(%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT))

(MAKE-HASH-TABLE :SIZE 2 :REHASH-SIZE -1.5)
ERROR

(MAKE-HASH-TABLE :SIZE 2 :REHASH-SIZE 0.5)
ERROR

(MAKE-HASH-TABLE :SIZE 2 :REHASH-SIZE 1.0)
#S(HASH-TABLE TEST EQL SIZE 2 %%SIZE 4 REHASH-SIZE 1.0 %%REHASH-SIZE 4
       REHASH-THRESHOLD 13 %%REHASH-THRESHOLD 2 %%COUNT 0 %%HASH-VEKTOR
       #(%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT))

(MAKE-HASH-TABLE :SIZE 2 :REHASH-SIZE 5)
#S(HASH-TABLE TEST EQL SIZE 2 %%SIZE 4 REHASH-SIZE 5 %%REHASH-SIZE 2
       REHASH-THRESHOLD 13 %%REHASH-THRESHOLD 2 %%COUNT 0 %%HASH-VEKTOR
       #(%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT))

(MAKE-HASH-TABLE :SIZE 4 :REHASH-SIZE 5.0)
#S(HASH-TABLE TEST EQL SIZE 4 %%SIZE 8 REHASH-SIZE 5.0 %%REHASH-SIZE 8
       REHASH-THRESHOLD 13 %%REHASH-THRESHOLD 3 %%COUNT 0 %%HASH-VEKTOR
       #(%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT))

(MAKE-HASH-TABLE :SIZE 2 :REHASH-SIZE NIL)
ERROR

(MAKE-HASH-TABLE :SIZE 2 :REHASH-THRESHOLD NIL)
ERROR

(MAKE-HASH-TABLE :%%SIZE 3)
#S(HASH-TABLE TEST EQL SIZE 16 %%SIZE 3 REHASH-SIZE 2.0 %%REHASH-SIZE 2
       REHASH-THRESHOLD 13 %%REHASH-THRESHOLD 13 %%COUNT 0 %%HASH-VEKTOR
       #(%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT))

(SETQ TAB (MAKE-HASH-TABLE))
#S(HASH-TABLE TEST EQL SIZE 16 %%SIZE 32 REHASH-SIZE 2.0 %%REHASH-SIZE 2
       REHASH-THRESHOLD 13 %%REHASH-THRESHOLD 13 %%COUNT 0 %%HASH-VEKTOR
       #(%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT))

(SETF-GETHASH (QUOTE HALLO) TAB (QUOTE WIEGWHTS))
WIEGWHTS

(SETF-GETHASH (QUOTE UHU) TAB (QUOTE KAUZ))
KAUZ

(GETHASH (QUOTE UHU) TAB)
KAUZ

(GETHASH UHU TAB)
ERROR

(MAKE-HASH-TABLE)
#S(HASH-TABLE TEST EQL SIZE 16 %%SIZE 32 REHASH-SIZE 2.0 %%REHASH-SIZE 2
       REHASH-THRESHOLD 13 %%REHASH-THRESHOLD 13 %%COUNT 0 %%HASH-VEKTOR
       #(%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT))

(SETQ TAB NIL)
NIL

(SETF-GETHASH (QUOTE UHU) TAB (QUOTE KAUS))
ERROR

(GETHASH (QUOTE UHU) TAB)
ERROR

(GETHASH (QUOTE OTTO) TAB)
ERROR

(SETQ TAB (MAKE-HASH-TABLE))
#S(HASH-TABLE TEST EQL SIZE 16 %%SIZE 32 REHASH-SIZE 2.0 %%REHASH-SIZE 2
       REHASH-THRESHOLD 13 %%REHASH-THRESHOLD 13 %%COUNT 0 %%HASH-VEKTOR
       #(%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT))

(SETF-GETHASH (QUOTE UHU) TAB (QUOTE KAUS))
KAUS

(GETHASH (QUOTE UHU) TAB)
KAUS

(GETHASH (QUOTE OTTO) TAB)
NIL

(SETF-GETHASH (QUOTE UHU) TAB (QUOTE KAUZ))
KAUZ

(SETF-GETHASH TAB)
ERROR

(REMHASH (QUOTE UHU) TAB)
T

TAB
#S(HASH-TABLE TEST EQL SIZE 16 %%SIZE 32 REHASH-SIZE 2.0 %%REHASH-SIZE 2
       REHASH-THRESHOLD 13 %%REHASH-THRESHOLD 13 %%COUNT 0 %%HASH-VEKTOR
       #(%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT))

(CLRHASH TAB9)
ERROR

(CLRHASH TAB)
#S(HASH-TABLE TEST EQL SIZE 16 %%SIZE 32 REHASH-SIZE 2.0 %%REHASH-SIZE 2
       REHASH-THRESHOLD 13 %%REHASH-THRESHOLD 13 %%COUNT 0 %%HASH-VEKTOR
       #(%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT))

(HASH-TABLE-COUNT TAB)
0

(SETF-GETHASH (QUOTE KLAK) TAB (QUOTE KLASE))
KLASE

(SETF-GETHASH (QUOTE KUNZE) TAB (QUOTE RIESE))
RIESE

(HASH-TABLE-P TAB)
T

(HASH-TABLE-COUNT TAB)
2

(REMHASH (QUOTE KUNZE) TAB)
T

(SETF-GETHASH (QUOTE WALD) TAB (QUOTE KHJGSFGJHDF))
KHJGSFGJHDF

(GETHASH)
ERROR

(REMHASH)
ERROR

(CLRHASH TAB)
#S(HASH-TABLE TEST EQL SIZE 16 %%SIZE 32 REHASH-SIZE 2.0 %%REHASH-SIZE 2
       REHASH-THRESHOLD 13 %%REHASH-THRESHOLD 13 %%COUNT 0 %%HASH-VEKTOR
       #(%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT
%%EMPTY-ELEMENT %%EMPTY-ELEMENT %%EMPTY-ELEMENT))

